export const data = [
  {
    id: 1,
    links: "timesonline.co.uk",
    prefix: "QB0GaK7",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 2,
    links: "merriam-webster.com",
    prefix: "8oUTDyz",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 3,
    links: "newyorker.com",
    prefix: "Z9i2o9o",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 4,
    links: "angelfire.com",
    prefix: "pW44f49",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 5,
    links: "rambler.ru",
    prefix: "w1vDJvP",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 6,
    links: "timesonline.co.uk",
    prefix: "Uz3Uq87",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 7,
    links: "state.gov",
    prefix: "PwT2wMc",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 8,
    links: "youtube.com",
    prefix: "c1TO1x6",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 9,
    links: "washingtonpost.com",
    prefix: "4KtfXaU",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 10,
    links: "icq.com",
    prefix: "nh294Ty",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 11,
    links: "cbsnews.com",
    prefix: "0e56PW3",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 12,
    links: "google.pl",
    prefix: "NNq9FXo",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 13,
    links: "uiuc.edu",
    prefix: "55b5FKK",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 14,
    links: "creativecommons.org",
    prefix: "0Q43Q2J",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 15,
    links: "cam.ac.uk",
    prefix: "1dYVlCo",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 16,
    links: "microsoft.com",
    prefix: "5leG2TS",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 17,
    links: "ebay.co.uk",
    prefix: "2tYI62f",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 18,
    links: "sitemeter.com",
    prefix: "rm9FWnh",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 19,
    links: "sitemeter.com",
    prefix: "T9iQsAc",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 20,
    links: "alexa.com",
    prefix: "5klAHT4",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 21,
    links: "go.com",
    prefix: "TAfH6S5",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 22,
    links: "cpanel.net",
    prefix: "gSHI03n",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 23,
    links: "wikispaces.com",
    prefix: "gIhOGLQ",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 24,
    links: "friendfeed.com",
    prefix: "Dzk33k6",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 25,
    links: "slate.com",
    prefix: "QlQm54c",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 26,
    links: "unc.edu",
    prefix: "7ZBQAXv",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 27,
    links: "skyrock.com",
    prefix: "qXL02fT",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 28,
    links: "posterous.com",
    prefix: "EVjCLOo",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 29,
    links: "google.pl",
    prefix: "TR6z1pS",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 30,
    links: "reverbnation.com",
    prefix: "osrL9jc",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 31,
    links: "time.com",
    prefix: "4oYLDF3",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 32,
    links: "cnn.com",
    prefix: "uB27DmP",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 33,
    links: "bbc.co.uk",
    prefix: "iU2f7Rg",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 34,
    links: "guardian.co.uk",
    prefix: "P3I9wBv",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 35,
    links: "forbes.com",
    prefix: "oD72JsX",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 36,
    links: "huffpost.com",
    prefix: "A5lC9Z1",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 37,
    links: "bloomberg.com",
    prefix: "V8k1TZ8",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 38,
    links: "wsj.com",
    prefix: "kD8aX4C",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 39,
    links: "nytimes.com",
    prefix: "nF5lZ7E",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
  {
    id: 40,
    links: "npr.org",
    prefix: "rX3pW4D",
    add_tags: [
      { tag: "Technology" },
      { tag: "Fashion" },
      { tag: "Food" },
      { tag: "Travel" },
      { tag: "Sports" },
      { tag: "Music" },
      { tag: "Art" },
      { tag: "Health" },
      { tag: "Education" },
      { tag: "Finance" },
    ],
    selected_tags: "",
  },
];
